### ISSUE TITLE
Spotify-Support

### ISSUE THREAD

**Issue by selmaohneh** [selmaohneh/DdfGuide#13]
Neben dem Gehört- und dem Favorit-Kästchen soll ein Spotify-Symbol hin, dass direkt die Folge in der Spotify-App start. Falls die App nicht installiert ist, soll zu der Web-App weitergeleitet werden.

Dafür müssen die entsprechenden URIs, soweit vorhanden, in die dtos.json eingetragen werden.

**Comment by selmaohneh** [comment]
Der Streamingdienst sollte entweder in den Einstellungen definiert werden, oder es sollten alle großen Dienste angeboten werden (Google Play, Amazon,...)

**Comment by ftpproxy** [comment]
Die konfigurierbare Lösung finde ich gut, da sonst die Albumansicht so voll wird.
Vielleicht sollte man die Implementierung der einzelnen Streaminganbieter aber stufenweise einführen.

**Comment by selmaohneh** [comment]
Stufenweise wird es dann auf jeden Fall mit Spotify losgehen. Eigeninteresse. 😂 Alle Spotifyuris einzupflegen ist aber initial ein ordentlicher Aufwand, wenn da nichts automatisiert erfolgen kann... Aber du hast ja bewiesen, dass du fleißig bist. 🙏

**Comment by ftpproxy** [comment]
Die URLs habe ich mir gerade schon per Script über die Spotify API exportiert. Das ist also überschaubar vom Aufwand..

**Comment by selmaohneh** [comment]
Die Logik zum Aufrufen der Uris stelle ich mir auch nicht sonderlich komplex vor zumal schon ein UriInvoker vorhanden ist, der aus der App zu Github weiterleitet. Ich denke sogar, dass bereits durch die Uri automatisch zur Spotify App weitergeleitet wird, falls diese installiert ist.
Es wird also auf Codeseite hauptsächlich etwas UI-Gefriemel.

**Comment by ftpproxy** [comment]
Wie sollen wir denn die Datenstruktur ändern? So?
   {
    "Id": "c8863869-d448-49a4-8770-ae2718d5ff76",
    "Title": "...und der Mottenmann",
    "NumberEuropa": 206,
    "ReleaseDate": "2020-07-17T00:00:00",
    "Interpreter": "Die drei ???",
    "CoverUrl": "https://github.com/selmaohneh/DdfGuide/raw/master/Covers/c8863869-d448-49a4-8770-ae2718d5ff76.jpg",
    "SpotifyUrl":"https://open.spotify.com/album/7khAMIQlYBmW7mI9cphDhJ",
...

Man könnte aber auch nur die ID des Albums hinterlegen und die URL dynamisch zusammen bauen. Also so:
...
"SpotifyAlbumID":"7khAMIQlYBmW7mI9cphDhJ",
...

Was denkst Du?

**Comment by selmaohneh** [comment]
Ja, nur die ID. Der Rest ist redundant. So haben wir auch flexibel, falls Spotify mal ihre URL ändert.
Als Propertyname finde ich SpotifyAlbumId oder einfach SpotifyId gut. Bitte mich ID sondern Id, sonst meckert mich ReSharper wegen der Schreibweise an.😁

**Comment by ftpproxy** [comment]
Ich habe es gerade mit einem Parser für https://dreifragezeichen.de probiert um an die URLs der anderen Streaming Dienste zu kommen. Die Datenqualität der Seite ist nur unterirdisch schlecht. Zumindest für Amazon Music muss ich mir was anderes überlegen. Das Problem: Es gibt bei Amazon keine freie API um nach den Alben eines Interpreten zu suchen, so wie bei Spotify. Oder ich habe diese Möglichkeit noch nicht entdeckt ...

**Comment by ftpproxy** [comment]
Das war jetzt echt aufwendig, aber ich habe nun eine vollständige Liste mit Amazon Music IDs für die ???.

URL Schema = https://music.amazon.de/albums/<AlbumID>

Als Property würde ich vorschlagen: AmazonAlbumId

**Comment by selmaohneh** [comment]
Habe eine erste Version implementiert!
![image](https://user-images.githubusercontent.com/29881939/94436610-f14fd900-019c-11eb-9f46-c6cbd70a624d.png)

Funktioniert prima... werde ich ein paar Tage testen und wenn keine Fehler auftauchen, dann release ich das. :-)

**Comment by selmaohneh** [comment]
Erledigt! 👍

**Comment by ftpproxy** [comment]
Das Readme sollte noch angepasst werden und über dieses coole neue Feature informieren!

**Comment by selmaohneh** [comment]
Oh, ja. Habe ich bisher nur im PlayStore gemacht. Ziehe ich nach!

**Comment by selmaohneh** [comment]
Done.
