### ISSUE TITLE
Die App unter einer freien Lizenz veröffentlichen

### ISSUE THREAD

**Issue by Mynacol** [selmaohneh/DdfGuide#16]
Hi @selmaohneh ,
bist du daran interessiert, die App unter einer freien Lizenz zu stellen?
Das GNU Projekt stellt [hier](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses) eine Liste freier Softwarelizenzen, die kompatibel mit der GNU GPL sind, zur Verfügung.
Mein Ziel wäre, die App auf [F-Droid](https://f-droid.org/de/) zu sehen.
Danke im Voraus,
Mynacol

**Comment by selmaohneh** [comment]
Moin!

Habe mir noch nie über Lizenzen Gedanken gemacht... Werde ich mir aber wohl mal durchlesen müssen. Da die App komplett Open Source ist und keinerlei finanzielle Interessen bestehen, kann ich mir das gut vorstellen...

**Comment by selmaohneh** [comment]
Ich müsste die Lizenz dann hier bei Github veröffentlichen!? Über F-Droid würdest du dich dann kümmern?

**Comment by selmaohneh** [comment]
Erledigt ab Version v2.6

**Comment by KerstinMaur** [comment]
Ich war mal so frei und habe die App bei F-Droid [vorgeschlagen](https://gitlab.com/fdroid/rfp/issues/967).
So eine coole App darf dort nicht fehlen. 😎

**Comment by selmaohneh** [comment]
@KerstinMaur Schankedön!

**Comment by KerstinMaur** [comment]
Kannst du eigentlich die gradle Datei auch auf GitHub veröffentlichen?

**Comment by selmaohneh** [comment]
@KerstinMaur Der DDF Guide ist ein Xamarin.Android-Projekt und hat keine gradle-Datei. 

https://stackoverflow.com/questions/38049536/gradle-dependencies-in-xamarin

Ergo werde ich auch nicht veröffentlichen können. :-/

**Comment by KerstinMaur** [comment]
Oh, kein Problem. Das klappt auch. 👌

**Comment by KerstinMaur** [comment]
Kannst du in Zukunft bitte bei den [Releases](https://github.com/selmaohneh/DdfGuide/releases) auch die .apk mit veröffentlichen?

**Comment by selmaohneh** [comment]
Ja, kann ich machen.

**Comment by KerstinMaur** [comment]
Hier mal ein Update: F-Droid kann leider noch immer keine Xamarin Projekte bauen.
Aber Izzy hat die App in sein [Repo](https://apt.izzysoft.de/fdroid/index/apk/celloapps.ddfguide) eingebunden, das sich die .apk direkt von deinen GitHub Releases lädt. Somit haben Nutzer ohne Google Play eine einfache Möglichkeit, den DDF Guide zu beziehen.

**Comment by selmaohneh** [comment]
@KerstinMaur Würdest du dazu ein paar Worte in die Readme schreiben? 🙏 Alternative Installationshinweise sind sicher für viele interessant. Lieben Dank! 😊

**Comment by KerstinMaur** [comment]
Sehr gerne! ☺️
Ich eröffne in der ersten [Oktober](https://hacktoberfest.digitalocean.com/)woche einen PR dafür.
