### ISSUE TITLE
Links/Rechts wischen zum Markieren als "gehört" bzw. "Favorit"  in der Listenansicht

### ISSUE THREAD

**Issue by selmaohneh** [selmaohneh/DdfGuide#31]
Viele vermissen das Feature, direkt in der Listenansicht Folgen als gehört oder Favorit zu markieren. 

Da Checkboxen in der Listenansicht gegen die Androidkonventionen sind, habe ich an Wischgesten gedacht.

Wischt man eine Folge nach links erscheint ein blauer Hintergrund und beim loslassen wird die Folge als gehört markiert.

Wischt man eine Folge nach rechts erscheint ein roter Hintergrund und beim loslassen wird die Folge als Favorit markiert.

Optional, je nach Aufwand, kann man in den farbigen Hintergrund auch noch das jeweilige Symbol packen (Herz/Box).

So könnte man sich wild durch die Liste wischen und schnell abhaken und hat trotzdem nicht den Nachteil, eine Folge versehentlich zu markieren.

**Comment by selmaohneh** [comment]
Implementiert. 

Die Icons habe ich nicht in die Swipe-Hintergründe gepackt. Das rote Herz wäre auf dem roten Hintergrund nicht zu sehen und das blaue Kästchen auf dem blauen ebenfalls nicht. Die Icon andersfarbig zu machen ist eher verwirrend als hilfreich.

**Comment by Mynacol** [comment]
Du könntest die Hintergründe in einem anderen Blau-/ Rotton färben. So ist das Icon zu erkennen und der Hintergrund signalisiert ebenfalls die Funktion.

**Comment by selmaohneh** [comment]
@Mynacol Joa, das könnte man machen.  Eventuell reicht es auch den Hintergrund eine Transparenz zu geben... 

Zusätzlicher Gedanke: Wenn man mit den Icons in den Hintergründen arbeitet, dann sollten die aber auch dynamisch den Zustand zeigen, der durch die Aktion ausgelöst wird. Ergo: Ist die Folge kein Favorit zeigt der Hintergrund ein gefülltes Herz, ist die Folge ein Favorit zeigt der Hintergrund nur den Herzrahmen. Bei gehört/nicht gehört analog.

Da das ganze dann doch Logik enthält und nicht nur eine Farbänderung ist, sollten wir dafür mal ein Ticket aufmachen...
