### ISSUE TITLE
Filter und Sortierung werden nach Neustart zurückgesetzt 

### ISSUE THREAD

**Issue by FranzMan** [selmaohneh/DdfGuide#6]
Filter und Sortierung werden nach Neustart zurückgesetzt. Leider sehr unpraktisch, wenn man es jedes mal neu einstellen muss.

**Comment by selmaohneh** [comment]
Das ist sicherlich Geschmackssache...

Falls wir sowas einbauen wollen, dann sicherlich optional. Ergo mit einem Einstellungsmenü.
