### ISSUE TITLE
Buchautoren hinzufügen

### ISSUE THREAD

**Issue by selmaohneh** [selmaohneh/DdfGuide#65]
Viele wünschen sich, nach Autoren suchen und filtern zu können. Grundbedingung dafür ist natürlich, dass die zunächst einmal eingepflegt werden.

**Comment by selmaohneh** [comment]
Wäre das nicht wieder was für dich, @ftpprox ? *liebguck*

**Comment by ftpproxy** [comment]
Schaue ich mir gerne an. Die erste Herausforderung wird sein, eine entsprechend Liste zu generieren. Ich suche mal im Netz danach.
