### ISSUE TITLE
Cover werden bei jedem Start neugeladen

### ISSUE THREAD

**Issue by FranzMan** [selmaohneh/DdfGuide#8]
Gibt es kein Möglichkeit diese dauerhaft zu speichern oder ist das ein rechtliches Problem?

**Comment by selmaohneh** [comment]
Das ist nicht ganz richtig. Die Cover sind auch lokal auf dem Gerät gecached, als auch offline verfügbar, sobald sie einmal geladen wurden! Das ganze gilt auch für die anderen Folgendetails. Details werden bei jedem Start, wenn möglich, aktualisiert. Cover erst nach einer gewissen Zeit, glaube einige Wochen...

**Comment by selmaohneh** [comment]
Habe ein Folgeticket, dass deiner Frage ähnelt geöffnet.

https://github.com/selmaohneh/DdfGuide/issues/10
